language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install msgpack-python
  - pip install sphinx

script:
  - python -m unittest -v tests
  - sphinx-build docs/source docs/html
