language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install msgpack-python pylint sphinx==1.4.1 sphinx-rtd-theme

script:
  - pylint --rcfile .pylintrc advancedhttpserver.py
  - python -m unittest -v tests
  - sphinx-build -b html -E docs/source docs/html
