language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install msgpack-python pylint sphinx==1.2.2

script:
  - pylint --rcfile .pylintrc AdvancedHTTPServer.py
  - python -m unittest -v tests
  - sphinx-build docs/source docs/html
